name: Validate via personal conftest policies
permissions: {}

'on':
  push:
    branches:
      - main
  pull_request:

env:
  CONFTEST_VERSION: "0.65.0"

jobs:
  conftest:
    name: Validate via personal conftest policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install conftest
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -sL "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" | tar xzf - -C "${HOME}/.local/bin" conftest
      - name: Validate via personal conftest policies
        env:
          CONFTEST_POLICIES: git::https://github.com/iamleot/conftest-policies.git//policy/github
        run: |
          conftest test --all-namespaces --update "${{ env.CONFTEST_POLICIES }}" .github
